name: ctcOpen
description: Open a CTC case for a release

inputs:
  SF_CHANGE_CASE_SFDX_AUTH_URL:
    description: Auth URL
    required: true
  SF_CHANGE_CASE_TEMPLATE_ID:
    description: Change Case template ID
    required: true
  SF_CHANGE_CASE_CONFIGURATION_ITEM:
    description: Change Case config item
    required: true
  SVC_CLI_BOT_GITHUB_TOKEN:
    description: Github token
    required: true

outputs:
  changeCaseId:
    description: Id for the change case created
    value: ${{ steps.ctc.outputs.ctcId }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.SVC_CLI_BOT_GITHUB_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - run: npm install -g @salesforce/change-case-management --omit=dev
      shell: bash

    - name: Open CTC case
      id: ctc
      uses: jayree/github-workflows/.github/actions/retry@jayree
      with:
        max_attempts: 5
        command: |
          CTC_RESULT=$(sfchangecase create --location ${{ github.repositoryUrl }} --release ${{ github.repository }}.$(date +%F) --json)

          STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
          CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')

          if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
              echo "Successfully created case with ID: $CTC_ID"
              echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
          else
              echo "CTC failed to open a case. Result:"
              echo "$CTC_RESULT"
              exit 1
          fi
      env:
        SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ inputs.SF_CHANGE_CASE_SFDX_AUTH_URL}}
        SF_CHANGE_CASE_TEMPLATE_ID: ${{ inputs.SF_CHANGE_CASE_TEMPLATE_ID}}
        SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ inputs.SF_CHANGE_CASE_CONFIGURATION_ITEM}}

    - run: echo "case id is ${{ steps.ctc.outputs.ctcId }}"
      shell: bash
