on:
  workflow_call:
    outputs:
      changeCaseId:
        description: Id for the change case created
        value: ${{ jobs.ctcOpen.outputs.changeCaseId }}

jobs:
  ctcOpen:
    outputs:
      changeCaseId: ${{ steps.ctc.outputs.ctcId }}
    runs-on: static-ip-ubuntu-runners
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm install -g @salesforce/change-case-management --omit=dev
      - name: Open CTC case
        id: ctc
        uses: jayree/github-workflows/.github/actions/retry@jayree
        with:
          max_attempts: 5
          command: |
            CTC_RESULT=$(sfchangecase create --location ${{github.repositoryUrl}} --release ${{github.repository}}.$(date +%F) --json)

            STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
            CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')

            if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
                echo "Successfully created case with ID: $CTC_ID"
                echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
            else
                echo "CTC failed to open a case. Result:"
                echo "$CTC_RESULT"
                exit 1
            fi
        env:
          SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ secrets.SF_CHANGE_CASE_SFDX_AUTH_URL}}
          SF_CHANGE_CASE_TEMPLATE_ID: ${{ secrets.SF_CHANGE_CASE_TEMPLATE_ID}}
          SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ secrets.SF_CHANGE_CASE_CONFIGURATION_ITEM}}
      - run: echo "case id is ${{ steps.ctc.outputs.ctcId }}"
