on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
        description: only needed if upload. sfdx or sf
      version:
        type: string
        required: true
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: true
        description: channel that the uploaded tarballs get promoted to
      nodeVersion:
        type: string
        default: lts/*
        description: node version to use for the tarball build

jobs:
  win:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      WINDOWS_SIGNING_KEY: ${{ secrets.WINDOWS_SIGNING_KEY }}
      SFDX_WINDOWS_SIGNING_PASS: ${{ secrets.SFDX_WINDOWS_SIGNING_PASS }}
      SF_WINDOWS_SIGNING_PASS: ${{ secrets.SF_WINDOWS_SIGNING_PASS }}
      SFDX_HIDE_RELEASE_NOTES: true
      SF_DISABLE_TELEMETRY: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@41775cf0c82ef066f1eb39cea1bd74697ca5b735
      - run: brew install makensis
      - uses: jayree/github-workflows/.github/actions/yarnInstallWithRetries@jayree
      - run: yarn pack:win
      - run: yarn upload:win
      - run: yarn channel:promote --cli ${{ inputs.cli }} --version ${{ inputs.version }} --target ${{ inputs.channel }} --platform win
        name: Promote win to ${{ inputs.channel }} channel
