on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        description: true means test, then upload them AWS
        required: false
      cli:
        type: string
        required: false
        description: only needed if upload. sfdx or sf
      version:
        type: string
        required: false
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: false
        description: channel that the uploaded tarballs get promoted to
      nodeVersion:
        type: string
        default: lts/*
        description: node version to use for the tarball build

jobs:
  tarballs:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SFDX_HIDE_RELEASE_NOTES: true
      SF_DISABLE_TELEMETRY: true
    runs-on: ubuntu-20-8core
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn
      - uses: jayree/github-workflows/.github/actions/yarnInstallWithRetries@jayree
      - name: pack tarballs
        uses: jayree/github-workflows/.github/actions/retry@jayree
        with:
          command: yarn pack:tarballs
          retry_on: error
      - run: yarn pack:verify
      - run: yarn test:smoke-unix
      - if: inputs.upload
        run: yarn upload:tarballs
      - if: inputs.upload && inputs.cli && inputs.version && inputs.channel
        run: yarn channel:promote --cli ${{ inputs.cli }} --version ${{ inputs.version }} --target ${{ inputs.channel }}
