on:
  workflow_call:

jobs:
  determine-node-versions:
    outputs:
      nodeVersions: ${{ steps.determine-node-versions.outputs.nodeVersions }}
    runs-on: ubuntu-latest
    steps:
      - uses: jayree/github-workflows/.github/actions/determineNodeVersions@jayree
        id: determine-node-versions
        with:
          nodeVersionOverride: ${{ vars.NODE_VERSION_OVERRIDE }} # default is 'lts/*' and 'lts/-1'
          nodeDisableCurrent: ${{ vars.UT_DISABLE_NODE_CURRENT }} # default is falsy

  linux-unit-tests:
    needs: determine-node-versions
    strategy:
      matrix:
        node_version: ${{ fromJSON(needs.determine-node-versions.outputs.nodeVersions) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - uses: google/wireit@setup-github-actions-caching/v1
        continue-on-error: true
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - uses: jayree/github-workflows/.github/actions/yarnInstallWithRetries@jayree
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn build
      - name: yarn test
        uses: jayree/github-workflows/.github/actions/retry@jayree
        with:
          command: yarn test
        env:
          SF_DISABLE_TELEMETRY: true
